refactor: rename plugin per krew request

diff --git a/kubectl-mdba b/kubectl-mdba
--- a/kubectl-mdba
+++ b/kubectl-mdba
@@ -1,20 +1,20 @@
 #!/usr/bin/env bash
 
-# kubectl-mdb is a kubectl plugin that helps interact
-# with mariadb-operator semi-sync replication clusters
+# kubectl-mdba is a kubectl plugin that helps manage
+# mariadb-operator semi-sync replication clusters
 
 [[ -n "${DEBUG}" ]] && set -x
 set -eo pipefail
 
 VERSION="0.0.4-dev"
 
-KMDB_KUBECTL="${KMDB_KUBECTL:-kubectl}"
-KMDB_NAMESPACE="${KMDB_NAMESPACE:-default}"
-KMDB_BACKUP_THREADS="${KMDB_BACKUP_THREADS:-1}"
-KMDB_BACKUP_DIR="${KMDB_BACKUP_DIR:-/var/lib/mysql/.kmdb_backup}"
-KMDB_RESTORE_DIR="${KMDB_RESTORE_DIR:-/var/lib/mysql/.kmdb_restore}"
-KMDB_STREAM_PORT="${KMDB_STREAM_PORT:-4444}"
-KMDB_IGNORE_PRIMARY_MISMATCH="${KMDB_IGNORE_PRIMARY_MISMATCH:-0}"
+KMDBA_KUBECTL="${KMDBA_KUBECTL:-kubectl}"
+KMDBA_NAMESPACE="${KMDBA_NAMESPACE:-default}"
+KMDBA_BACKUP_THREADS="${KMDBA_BACKUP_THREADS:-1}"
+KMDBA_BACKUP_DIR="${KMDBA_BACKUP_DIR:-/var/lib/mysql/.kmdba_backup}"
+KMDBA_RESTORE_DIR="${KMDBA_RESTORE_DIR:-/var/lib/mysql/.kmdba_restore}"
+KMDBA_STREAM_PORT="${KMDBA_STREAM_PORT:-4444}"
+KMDBA_IGNORE_PRIMARY_MISMATCH="${KMDBA_IGNORE_PRIMARY_MISMATCH:-0}"
 
 # colors
 RED=$(tput setaf 1)
@@ -29,10 +29,10 @@ RES=$(tput sgr0)
 # arg: none
 show_help() {
   cat << EOF | colorize "man"
-kubectl mdb helps interact with mariadb-operator semi-sync replication clusters
+kubectl mdba helps manage mariadb-operator semi-sync replication clusters
 
 Usage:
-  kubectl mdb <command> [<target>]
+  kubectl mdba <command> [<target>]
 
 Commands:
 $(awk '/^####/ {$1=""; print}' "$0" \
@@ -53,30 +53,30 @@ EOF
 ### show version and exit
 # arg: none
 show_version() {
-  echo "kubectl mdb version v${VERSION}"
+  echo "kubectl mdba version v${VERSION}"
   exit 0
 }
 
 ### validate crucial global vars
 # arg: none
 check_globals() {
-  [[ "${KMDB_BACKUP_THREADS}" =~ ^[1-8]$ ]] || err "KMDB_BACKUP_THREADS is not allowed integer {1..8}: ${KMDB_BACKUP_THREADS}"
-  [[ "${KMDB_IGNORE_PRIMARY_MISMATCH}" =~ ^(0|1)$ ]] || err "KMDB_IGNORE_PRIMARY_MISMATCH is not allowed integer {0..1}: ${KMDB_IGNORE_PRIMARY_MISMATCH}"
+  [[ "${KMDBA_BACKUP_THREADS}" =~ ^[1-8]$ ]] || err "KMDBA_BACKUP_THREADS is not allowed integer {1..8}: ${KMDBA_BACKUP_THREADS}"
+  [[ "${KMDBA_IGNORE_PRIMARY_MISMATCH}" =~ ^(0|1)$ ]] || err "KMDBA_IGNORE_PRIMARY_MISMATCH is not allowed integer {0..1}: ${KMDBA_IGNORE_PRIMARY_MISMATCH}"
 
-  [[ "${KMDB_STREAM_PORT}" =~ ^[0-9]+$ \
-    && "${KMDB_STREAM_PORT}" -ne 3306
-    && "${KMDB_STREAM_PORT}" -gt 1024 \
-    && "${KMDB_STREAM_PORT}" -le 65535 ]] || err "KMDB_STREAM_PORT is not allowed integer {1024..65535}: ${KMDB_STREAM_PORT}"
+  [[ "${KMDBA_STREAM_PORT}" =~ ^[0-9]+$ \
+    && "${KMDBA_STREAM_PORT}" -ne 3306
+    && "${KMDBA_STREAM_PORT}" -gt 1024 \
+    && "${KMDBA_STREAM_PORT}" -le 65535 ]] || err "KMDBA_STREAM_PORT is not allowed integer {1024..65535}: ${KMDBA_STREAM_PORT}"
 
-  [[ "${KMDB_BACKUP_DIR}" =~ ^/var/lib/mysql/.* ]] || err "KMDB_BACKUP_DIR is not within /var/lib/mysql/: ${KMDB_BACKUP_DIR}"
-  [[ "${KMDB_RESTORE_DIR}" =~ ^/var/lib/mysql/.* ]] || err "KMDB_RESTORE_DIR is not within /var/lib/mysql/: ${KMDB_RESTORE_DIR}"
+  [[ "${KMDBA_BACKUP_DIR}" =~ ^/var/lib/mysql/.* ]] || err "KMDBA_BACKUP_DIR is not within /var/lib/mysql/: ${KMDBA_BACKUP_DIR}"
+  [[ "${KMDBA_RESTORE_DIR}" =~ ^/var/lib/mysql/.* ]] || err "KMDBA_RESTORE_DIR is not within /var/lib/mysql/: ${KMDBA_RESTORE_DIR}"
 }
 
 ### ensure that core dependencies are installed
 # arg: none
 check_dependencies() {
   hash jq 2>/dev/null || err "dependency 'https://github.com/jqlang/jq' is not available"
-  hash "${KMDB_KUBECTL}" 2>/dev/null || err "dependency '${KMDB_KUBECTL}' is not available"
+  hash "${KMDBA_KUBECTL}" 2>/dev/null || err "dependency '${KMDBA_KUBECTL}' is not available"
 }
 
 ### colorize the input based on the given linter format
@@ -152,19 +152,19 @@ confirm() {
 
 ### parse and validate the input
 # arg: $@ - arguments
-# set: COMMAND, TARGET, KMDB_NAMESPACE, KMDB_IGNORE_PRIMARY_MISMATCH
+# set: COMMAND, TARGET, KMDBA_NAMESPACE, KMDBA_IGNORE_PRIMARY_MISMATCH
 parse_input() {
   while (( "$#" )); do
     case "$1" in
       -n|--namespace)
         if [[ -n "$2" ]] && [[ "${2:0:1}" != "-" ]]; then
-          KMDB_NAMESPACE="$2"; shift 2
+          KMDBA_NAMESPACE="$2"; shift 2
         else
           err "option $1 requires an argument"
         fi
         ;;
       -f|--force)
-        KMDB_IGNORE_PRIMARY_MISMATCH=1; shift
+        KMDBA_IGNORE_PRIMARY_MISMATCH=1; shift
         ;;
       -v|--version)
         show_version
@@ -207,11 +207,11 @@ get_pod() {
 
   pod="$1"; shift
 
-  POD=$("${KMDB_KUBECTL}" --namespace "${KMDB_NAMESPACE}" get pod "${pod}" --ignore-not-found --output json)
-  [[ -n "${POD}" ]] || err "pod '${pod}' not found in '${KMDB_NAMESPACE}' namespace"
+  POD=$("${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" get pod "${pod}" --ignore-not-found --output json)
+  [[ -n "${POD}" ]] || err "pod '${pod}' not found in '${KMDBA_NAMESPACE}' namespace"
 
   jq --exit-status '.metadata.labels["app.kubernetes.io/name"] == "mariadb"' <<< "${POD}" >/dev/null \
-    || err "pod '${pod}' in '${KMDB_NAMESPACE}' namespace is not a mariadb pod"
+    || err "pod '${pod}' in '${KMDBA_NAMESPACE}' namespace is not a mariadb pod"
 
   POD_IP=$(jq --raw-output '.status.podIP' <<< "${POD}")
 }
@@ -224,8 +224,8 @@ get_mariadb() {
 
   mariadb="$1"; shift
 
-  MARIADB=$("${KMDB_KUBECTL}" --namespace "${KMDB_NAMESPACE}" get mariadb "${mariadb}" --ignore-not-found --output json)
-  [[ -n "${MARIADB}" ]] || err "mariadb '${mariadb}' not found in '${KMDB_NAMESPACE}' namespace"
+  MARIADB=$("${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" get mariadb "${mariadb}" --ignore-not-found --output json)
+  [[ -n "${MARIADB}" ]] || err "mariadb '${mariadb}' not found in '${KMDBA_NAMESPACE}' namespace"
 
   MARIADB_REPLICATION=$(jq --raw-output '.spec.replication.enabled' <<< "${MARIADB}")
   MARIADB_SUSPEND=$(jq --raw-output '.spec.suspend' <<< "${MARIADB}")
@@ -240,7 +240,7 @@ is_replication_enabled() {
 
   mariadb="${TARGET}"
 
-  [[ "${MARIADB_REPLICATION}" == "true" ]] || err "semi-sync replication is disabled for mariadb '${mariadb}' in '${KMDB_NAMESPACE}' namespace"
+  [[ "${MARIADB_REPLICATION}" == "true" ]] || err "semi-sync replication is disabled for mariadb '${mariadb}' in '${KMDBA_NAMESPACE}' namespace"
 }
 
 ### check if mariadb is suspended
@@ -257,7 +257,7 @@ is_suspended() {
 # arg: none
 is_primary_index_mismatched() {
   if [[ "${MARIADB_DESIRED_PRIMARY_INDEX}" -ne "${MARIADB_CURRENT_PRIMARY_INDEX}" ]]; then
-    if (( KMDB_IGNORE_PRIMARY_MISMATCH )); then
+    if (( KMDBA_IGNORE_PRIMARY_MISMATCH )); then
       confirm "ignore mismatched desired '${MARIADB_DESIRED_PRIMARY_INDEX}' and current '${MARIADB_CURRENT_PRIMARY_INDEX}' primary pod indexes"
       return
     fi
@@ -275,7 +275,7 @@ is_replica() {
   pod_index="${pod##*-}"
 
   if [[ "${pod_index}" -eq "${MARIADB_CURRENT_PRIMARY_INDEX}" ]]; then
-    err "pod '${pod}' in '${KMDB_NAMESPACE}' namespace is not a replica"
+    err "pod '${pod}' in '${KMDBA_NAMESPACE}' namespace is not a replica"
   fi
 }
 
@@ -288,7 +288,7 @@ exec_pod() {
   pod="$1"; shift
   command=("$@"); shift "$#"
 
-  "${KMDB_KUBECTL}" --namespace "${KMDB_NAMESPACE}" exec "${pod}" --stdin --tty --container mariadb -- "${command[@]}"
+  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" exec "${pod}" --stdin --tty --container mariadb -- "${command[@]}"
 }
 
 ### run a sql query in a mariadb pod
@@ -310,9 +310,9 @@ suspend_mariadb() {
 
   mariadb="$1"; shift
 
-  "${KMDB_KUBECTL}" --namespace "${KMDB_NAMESPACE}" patch mariadb "${mariadb}" --type json \
+  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" patch mariadb "${mariadb}" --type json \
     --patch='[{"op": "replace", "path": "/spec/suspend", "value": true}]' \
-      || err "failed to suspend mariadb '${mariadb}' in '${KMDB_NAMESPACE}' namespace"
+      || err "failed to suspend mariadb '${mariadb}' in '${KMDBA_NAMESPACE}' namespace"
 }
 
 ### suspend mariadb reconciliation
@@ -322,9 +322,9 @@ unsuspend_mariadb() {
 
   mariadb="$1"; shift
 
-  "${KMDB_KUBECTL}" --namespace "${KMDB_NAMESPACE}" patch mariadb "${mariadb}" --type json \
+  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" patch mariadb "${mariadb}" --type json \
     --patch='[{"op": "replace", "path": "/spec/suspend", "value": false}]' \
-      || err "failed to unsuspend mariadb '${mariadb}' in '${KMDB_NAMESPACE}' namespace"
+      || err "failed to unsuspend mariadb '${mariadb}' in '${KMDBA_NAMESPACE}' namespace"
 }
 
 #============================================#
@@ -334,11 +334,11 @@ unsuspend_mariadb() {
 #### ls [<mariadb>] - list mariadbs with their pods
 # arg: none
 mdb_ls() {
-  "${KMDB_KUBECTL}" --namespace "${KMDB_NAMESPACE}" get mariadbs --ignore-not-found \
+  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" get mariadbs --ignore-not-found \
     | awk "NR == 1 || \$1 ~ /${TARGET:-.}/" \
     | colorize "VimHelp"
   echo
-  "${KMDB_KUBECTL}" --namespace "${KMDB_NAMESPACE}" get pods --selector app.kubernetes.io/name=mariadb --ignore-not-found --output wide \
+  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" get pods --selector app.kubernetes.io/name=mariadb --ignore-not-found --output wide \
     | awk "NR == 1 || \$1 ~ /${TARGET:-.}/" \
     | colorize "VimHelp"
 }
@@ -372,7 +372,7 @@ mdb_suspend() {
   if ! is_suspended; then
     suspend_mariadb "${mariadb}"
   else
-    err "mariadb '${mariadb}' in '${KMDB_NAMESPACE}' namespace is already suspended"
+    err "mariadb '${mariadb}' in '${KMDBA_NAMESPACE}' namespace is already suspended"
   fi
 }
 
@@ -388,7 +388,7 @@ mdb_unsuspend() {
   if is_suspended; then
     unsuspend_mariadb "${mariadb}"
   else
-    err "mariadb '${mariadb}' in '${KMDB_NAMESPACE}' namespace is not suspended"
+    err "mariadb '${mariadb}' in '${KMDBA_NAMESPACE}' namespace is not suspended"
   fi
 }
 
@@ -439,7 +439,7 @@ mdb_du() {
 #### top [<pod>] - display cpu and ram usage
 # arg: none
 mdb_top() {
-  "${KMDB_KUBECTL}" --namespace "${KMDB_NAMESPACE}" top pods --selector app.kubernetes.io/name=mariadb --containers \
+  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" top pods --selector app.kubernetes.io/name=mariadb --containers \
     | sed 's/(cores)\|(bytes)//g' \
     | column -t \
     | awk "NR == 1 || \$1 ~ /${TARGET:-.}/" \
@@ -484,9 +484,9 @@ mdb_prom() {
   is_replica "${replica}"
   is_primary_index_mismatched
 
-  confirm "promote replica pod '${replica}' in '${KMDB_NAMESPACE}' namespace to primary"
+  confirm "promote replica pod '${replica}' in '${KMDBA_NAMESPACE}' namespace to primary"
 
-  "${KMDB_KUBECTL}" --namespace "${KMDB_NAMESPACE}" patch mariadb "${mariadb}" --type json \
+  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" patch mariadb "${mariadb}" --type json \
     --patch='[{"op": "replace", "path": "/spec/replication/primary/podIndex", "value": '"${replica_index}"'}]'
 }
 
@@ -511,7 +511,7 @@ mdb_recreate() {
 
   get_pod "${primary}"
 
-  confirm "recreate replica pod '${replica}' in '${KMDB_NAMESPACE}' namespace from primary pod '${primary}'"
+  confirm "recreate replica pod '${replica}' in '${KMDBA_NAMESPACE}' namespace from primary pod '${primary}'"
 
   log_file=$(mktemp)
   echo "$(highlight "${CYA}" "⦿ log:") ${log_file}"
@@ -519,10 +519,10 @@ mdb_recreate() {
   {
 
   step "${step_num}" "replica" "${replica}" "Looking for leftovers from previous attempts"
-  exec_pod "${replica}" sh -c "test ! -e ${KMDB_BACKUP_DIR}" \
-    || err "please remove '${KMDB_BACKUP_DIR}' directory"
-  exec_pod "${replica}" sh -c "test ! -e ${KMDB_RESTORE_DIR}" \
-    || err "please remove '${KMDB_RESTORE_DIR}' directory"
+  exec_pod "${replica}" sh -c "test ! -e ${KMDBA_BACKUP_DIR}" \
+    || err "please remove '${KMDBA_BACKUP_DIR}' directory"
+  exec_pod "${replica}" sh -c "test ! -e ${KMDBA_RESTORE_DIR}" \
+    || err "please remove '${KMDBA_RESTORE_DIR}' directory"
   (( step_num +=1 ))
 
   step "${step_num}" "cluster" "${mariadb}" "Pausing reconciliation by mariadb-operator"
@@ -538,45 +538,45 @@ mdb_recreate() {
   (( step_num +=1 ))
 
   step "${step_num}" "replica" "${replica}" "Preparing to receive the backup stream from primary '${primary}'"
-  exec_pod "${replica}" nohup sh -c "mkdir --parents ${KMDB_BACKUP_DIR} && socat -u TCP-LISTEN:${KMDB_STREAM_PORT},reuseaddr stdio | mbstream --parallel=${KMDB_BACKUP_THREADS} --extract --directory=${KMDB_BACKUP_DIR} &" \
+  exec_pod "${replica}" nohup sh -c "mkdir --parents ${KMDBA_BACKUP_DIR} && socat -u TCP-LISTEN:${KMDBA_STREAM_PORT},reuseaddr stdio | mbstream --parallel=${KMDBA_BACKUP_THREADS} --extract --directory=${KMDBA_BACKUP_DIR} &" \
     || err "failed to create the receiver pipeline"
   (( step_num +=1 ))
 
-  step "${step_num}" "primary" "${primary}" "Starting the backup stream to replica '${replica}:${KMDB_STREAM_PORT}:${KMDB_BACKUP_DIR}'"
-  exec_pod "${primary}" sh -c "mariadb-backup --parallel=${KMDB_BACKUP_THREADS} --skip-ssl --backup --user=root --password=\${MARIADB_ROOT_PASSWORD} --stream=xbstream | socat -u stdio TCP:${replica_ip}:${KMDB_STREAM_PORT}" \
+  step "${step_num}" "primary" "${primary}" "Starting the backup stream to replica '${replica}:${KMDBA_STREAM_PORT}:${KMDBA_BACKUP_DIR}'"
+  exec_pod "${primary}" sh -c "mariadb-backup --parallel=${KMDBA_BACKUP_THREADS} --skip-ssl --backup --user=root --password=\${MARIADB_ROOT_PASSWORD} --stream=xbstream | socat -u stdio TCP:${replica_ip}:${KMDBA_STREAM_PORT}" \
     || err "backup stream has failed"
   (( step_num +=1 ))
 
-  step "${step_num}" "replica" "${replica}" "Preparing the backup in '${KMDB_BACKUP_DIR}'"
-  exec_pod "${replica}" sh -c "mariadb-backup --skip-ssl --target-dir=${KMDB_BACKUP_DIR} --prepare" \
+  step "${step_num}" "replica" "${replica}" "Preparing the backup in '${KMDBA_BACKUP_DIR}'"
+  exec_pod "${replica}" sh -c "mariadb-backup --skip-ssl --target-dir=${KMDBA_BACKUP_DIR} --prepare" \
     || err "failed to prepare the backup"
   (( step_num +=1 ))
 
   step "${step_num}" "replica" "${replica}" "Retrieving the last change GTID"
-  gtid=$(exec_pod "${replica}" sh -c "awk '{print \$NF}' ${KMDB_BACKUP_DIR}/mariadb_backup_binlog_info" | tr -d '\r') \
+  gtid=$(exec_pod "${replica}" sh -c "awk '{print \$NF}' ${KMDBA_BACKUP_DIR}/mariadb_backup_binlog_info" | tr -d '\r') \
     || err "failed to retrieve the last change GTID"
   [[ -n "${gtid}" ]] || err "failed to retrieve the last change GTID"
   (( step_num +=1 ))
 
-  step "${step_num}" "replica" "${replica}" "Restoring the backup to '${KMDB_RESTORE_DIR}'"
-  exec_pod "${replica}" sh -c "mariadb-backup --skip-ssl --target-dir=${KMDB_BACKUP_DIR} --datadir=${KMDB_RESTORE_DIR} --move-back" \
+  step "${step_num}" "replica" "${replica}" "Restoring the backup to '${KMDBA_RESTORE_DIR}'"
+  exec_pod "${replica}" sh -c "mariadb-backup --skip-ssl --target-dir=${KMDBA_BACKUP_DIR} --datadir=${KMDBA_RESTORE_DIR} --move-back" \
     || err "failed to restore the backup"
   (( step_num +=1 ))
 
-  step "${step_num}" "replica" "${replica}" "Moving the restored backup from '${KMDB_RESTORE_DIR}' to '/var/lib/mysql'"
-  exec_pod "${replica}" sh -c "rm --recursive --force /var/lib/mysql/*; mv ${KMDB_RESTORE_DIR}/* /var/lib/mysql" \
+  step "${step_num}" "replica" "${replica}" "Moving the restored backup from '${KMDBA_RESTORE_DIR}' to '/var/lib/mysql'"
+  exec_pod "${replica}" sh -c "rm --recursive --force /var/lib/mysql/*; mv ${KMDBA_RESTORE_DIR}/* /var/lib/mysql" \
     || err "failed to move the restored backup"
   (( step_num +=1 ))
 
-  step "${step_num}" "replica" "${replica}" "Removing temporary directories '${KMDB_BACKUP_DIR}' and '${KMDB_RESTORE_DIR}'"
-  exec_pod "${replica}" sh -c "rm --recursive --force ${KMDB_BACKUP_DIR} ${KMDB_RESTORE_DIR}" \
+  step "${step_num}" "replica" "${replica}" "Removing temporary directories '${KMDBA_BACKUP_DIR}' and '${KMDBA_RESTORE_DIR}'"
+  exec_pod "${replica}" sh -c "rm --recursive --force ${KMDBA_BACKUP_DIR} ${KMDBA_RESTORE_DIR}" \
     || err "failed to remove temporary directories"
   (( step_num +=1 ))
 
   step "${step_num}" "replica" "${replica}" "Recreating the pod"
-  "${KMDB_KUBECTL}" --namespace "${KMDB_NAMESPACE}" delete pod "${replica}" \
+  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" delete pod "${replica}" \
     || err "failed to delete the pod"
-  "${KMDB_KUBECTL}" --namespace "${KMDB_NAMESPACE}" wait --for condition=ready pod "${replica}" --timeout=3m \
+  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" wait --for condition=ready pod "${replica}" --timeout=3m \
     || err "the new pod failed to become ready"
   (( step_num +=1 ))
 
