feat: allow to start recreate from specific step

diff --git a/kubectl-mdba b/kubectl-mdba
--- a/kubectl-mdba
+++ b/kubectl-mdba
@@ -10,6 +10,7 @@ VERSION="0.0.5-dev"
 
 KMDBA_KUBECTL="${KMDBA_KUBECTL:-kubectl}"
 KMDBA_NAMESPACE="${KMDBA_NAMESPACE:-default}"
+KMDBA_RECREATE_STEP="${KMDBA_RECREATE_STEP:-1}"
 KMDBA_BACKUP_THREADS="${KMDBA_BACKUP_THREADS:-1}"
 KMDBA_BACKUP_DIR="${KMDBA_BACKUP_DIR:-/var/lib/mysql/.kmdba_backup}"
 KMDBA_RESTORE_DIR="${KMDBA_RESTORE_DIR:-/var/lib/mysql/.kmdba_restore}"
@@ -62,6 +63,11 @@ show_version() {
 check_globals() {
   [[ "${KMDBA_BACKUP_THREADS}" =~ ^[1-8]$ ]] || err "KMDBA_BACKUP_THREADS is not allowed integer {1..8}: ${KMDBA_BACKUP_THREADS}"
   [[ "${KMDBA_IGNORE_PRIMARY_MISMATCH}" =~ ^(0|1)$ ]] || err "KMDBA_IGNORE_PRIMARY_MISMATCH is not allowed integer {0..1}: ${KMDBA_IGNORE_PRIMARY_MISMATCH}"
+  [[ "${KMDBA_RECREATE_STEP}" =~ ^([1-9]|1[0-4])$ ]] || err "KMDBA_RECREATE_STEP is not allowed integer {1..14}: ${KMDBA_RECREATE_STEP}"
+
+  if [[ "${KMDBA_RECREATE_STEP}" -ge 8 ]] && [[ "${KMDBA_RECREATE_STEP}" -le 12 ]]; then
+    [[ -n "${KMDBA_GTID}" ]] || err "KMDBA_GTID is not set, but it is required because of KMDBA_RECREATE_STEP=${KMDBA_RECREATE_STEP}"
+  fi
 
   [[ "${KMDBA_STREAM_PORT}" =~ ^[0-9]+$ \
     && "${KMDBA_STREAM_PORT}" -ne 3306
@@ -518,82 +524,124 @@ mdb_recreate() {
 
   {
 
-  step "${step_num}" "replica" "${replica}" "Looking for leftovers from previous attempts"
-  exec_pod "${replica}" sh -c "test ! -e ${KMDBA_BACKUP_DIR}" \
-    || err "please remove '${KMDBA_BACKUP_DIR}' directory"
-  exec_pod "${replica}" sh -c "test ! -e ${KMDBA_RESTORE_DIR}" \
-    || err "please remove '${KMDBA_RESTORE_DIR}' directory"
-  (( step_num +=1 ))
-
-  step "${step_num}" "cluster" "${mariadb}" "Pausing reconciliation by mariadb-operator"
-  if ! is_suspended; then
-    suspend_mariadb "${mariadb}"
+  # step 1
+  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
+    step "${step_num}" "replica" "${replica}" "Looking for leftovers from previous attempts"
+    exec_pod "${replica}" sh -c "test ! -e ${KMDBA_BACKUP_DIR}" \
+      || err "please remove '${KMDBA_BACKUP_DIR}' directory"
+    exec_pod "${replica}" sh -c "test ! -e ${KMDBA_RESTORE_DIR}" \
+      || err "please remove '${KMDBA_RESTORE_DIR}' directory"
   fi
   (( step_num +=1 ))
 
-  step "${step_num}" "replica" "${replica}" "Dropping databases to free up disk space"
-  exec_pod "${replica}" sh -c "mariadb --skip-ssl --user=root --password=\${MARIADB_ROOT_PASSWORD} --batch --skip-column-names --execute='SHOW DATABASES WHERE Database NOT IN (\"information_schema\", \"performance_schema\", \"mysql\", \"sys\");' \
-    | xargs --no-run-if-empty --replace mariadb --skip-ssl --user=root --password=\${MARIADB_ROOT_PASSWORD} --execute='DROP DATABASE \`{}\`;'" \
-    || err "failed to drop databases"
+  # step 2
+  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
+    step "${step_num}" "cluster" "${mariadb}" "Pausing reconciliation by mariadb-operator"
+    if ! is_suspended; then
+      suspend_mariadb "${mariadb}"
+    fi
+  fi
   (( step_num +=1 ))
 
-  step "${step_num}" "replica" "${replica}" "Preparing to receive the backup stream from primary '${primary}'"
-  exec_pod "${replica}" nohup sh -c "mkdir --parents ${KMDBA_BACKUP_DIR} && socat -u TCP-LISTEN:${KMDBA_STREAM_PORT},reuseaddr stdio | mbstream --parallel=${KMDBA_BACKUP_THREADS} --extract --directory=${KMDBA_BACKUP_DIR} &" \
-    || err "failed to create the receiver pipeline"
+  # step 3
+  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
+    step "${step_num}" "replica" "${replica}" "Dropping databases to free up disk space"
+    exec_pod "${replica}" sh -c "mariadb --skip-ssl --user=root --password=\${MARIADB_ROOT_PASSWORD} --batch --skip-column-names --execute='SHOW DATABASES WHERE Database NOT IN (\"information_schema\", \"performance_schema\", \"mysql\", \"sys\");' \
+      | xargs --no-run-if-empty --replace mariadb --skip-ssl --user=root --password=\${MARIADB_ROOT_PASSWORD} --execute='DROP DATABASE \`{}\`;'" \
+      || err "failed to drop databases"
+  fi
   (( step_num +=1 ))
 
-  step "${step_num}" "primary" "${primary}" "Starting the backup stream to replica '${replica}:${KMDBA_STREAM_PORT}:${KMDBA_BACKUP_DIR}'"
-  exec_pod "${primary}" sh -c "mariadb-backup --parallel=${KMDBA_BACKUP_THREADS} --skip-ssl --backup --user=root --password=\${MARIADB_ROOT_PASSWORD} --stream=xbstream | socat -u stdio TCP:${replica_ip}:${KMDBA_STREAM_PORT}" \
-    || err "backup stream has failed"
+  # step 4
+  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
+    step "${step_num}" "replica" "${replica}" "Preparing to receive the backup stream from primary '${primary}'"
+    exec_pod "${replica}" nohup sh -c "mkdir --parents ${KMDBA_BACKUP_DIR} && socat -u TCP-LISTEN:${KMDBA_STREAM_PORT},reuseaddr stdio | mbstream --parallel=${KMDBA_BACKUP_THREADS} --extract --directory=${KMDBA_BACKUP_DIR} &" \
+      || err "failed to create the receiver pipeline"
+  fi
   (( step_num +=1 ))
 
-  step "${step_num}" "replica" "${replica}" "Preparing the backup in '${KMDBA_BACKUP_DIR}'"
-  exec_pod "${replica}" sh -c "mariadb-backup --skip-ssl --target-dir=${KMDBA_BACKUP_DIR} --prepare" \
-    || err "failed to prepare the backup"
+  # step 5
+  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
+    step "${step_num}" "primary" "${primary}" "Starting the backup stream to replica '${replica}:${KMDBA_STREAM_PORT}:${KMDBA_BACKUP_DIR}'"
+    exec_pod "${primary}" sh -c "mariadb-backup --parallel=${KMDBA_BACKUP_THREADS} --skip-ssl --backup --user=root --password=\${MARIADB_ROOT_PASSWORD} --stream=xbstream | socat -u stdio TCP:${replica_ip}:${KMDBA_STREAM_PORT}" \
+      || err "backup stream has failed"
+  fi
   (( step_num +=1 ))
 
-  step "${step_num}" "replica" "${replica}" "Retrieving the last change GTID"
-  gtid=$(exec_pod "${replica}" sh -c "awk '{print \$NF}' ${KMDBA_BACKUP_DIR}/mariadb_backup_binlog_info" | tr -d '\r') \
-    || err "failed to retrieve the last change GTID"
-  [[ -n "${gtid}" ]] || err "failed to retrieve the last change GTID"
+  # step 6
+  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
+    step "${step_num}" "replica" "${replica}" "Preparing the backup in '${KMDBA_BACKUP_DIR}'"
+    exec_pod "${replica}" sh -c "mariadb-backup --skip-ssl --target-dir=${KMDBA_BACKUP_DIR} --prepare" \
+      || err "failed to prepare the backup"
+  fi
   (( step_num +=1 ))
 
-  step "${step_num}" "replica" "${replica}" "Restoring the backup to '${KMDBA_RESTORE_DIR}'"
-  exec_pod "${replica}" sh -c "mariadb-backup --skip-ssl --target-dir=${KMDBA_BACKUP_DIR} --datadir=${KMDBA_RESTORE_DIR} --move-back" \
-    || err "failed to restore the backup"
+  # step 7
+  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
+    step "${step_num}" "replica" "${replica}" "Retrieving the last change GTID"
+    KMDBA_GTID=$(exec_pod "${replica}" sh -c "awk '{print \$NF}' ${KMDBA_BACKUP_DIR}/mariadb_backup_binlog_info" | tr -d '\r') \
+      || err "failed to retrieve the last change GTID"
+    [[ -n "${KMDBA_GTID}" ]] || err "failed to retrieve the last change GTID"
+  fi
   (( step_num +=1 ))
 
-  step "${step_num}" "replica" "${replica}" "Moving the restored backup from '${KMDBA_RESTORE_DIR}' to '/var/lib/mysql'"
-  exec_pod "${replica}" sh -c "rm --recursive --force /var/lib/mysql/*; mv ${KMDBA_RESTORE_DIR}/* /var/lib/mysql" \
-    || err "failed to move the restored backup"
+  # step 8
+  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
+    step "${step_num}" "replica" "${replica}" "Restoring the backup to '${KMDBA_RESTORE_DIR}'"
+    exec_pod "${replica}" sh -c "mariadb-backup --skip-ssl --target-dir=${KMDBA_BACKUP_DIR} --datadir=${KMDBA_RESTORE_DIR} --move-back" \
+      || err "failed to restore the backup"
+  fi
   (( step_num +=1 ))
 
-  step "${step_num}" "replica" "${replica}" "Removing temporary directories '${KMDBA_BACKUP_DIR}' and '${KMDBA_RESTORE_DIR}'"
-  exec_pod "${replica}" sh -c "rm --recursive --force ${KMDBA_BACKUP_DIR} ${KMDBA_RESTORE_DIR}" \
-    || err "failed to remove temporary directories"
+  # step 9
+  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
+    step "${step_num}" "replica" "${replica}" "Moving the restored backup from '${KMDBA_RESTORE_DIR}' to '/var/lib/mysql'"
+    exec_pod "${replica}" sh -c "rm --recursive --force /var/lib/mysql/*; mv ${KMDBA_RESTORE_DIR}/* /var/lib/mysql" \
+      || err "failed to move the restored backup"
+  fi
   (( step_num +=1 ))
 
-  step "${step_num}" "replica" "${replica}" "Recreating the pod"
-  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" delete pod "${replica}" \
-    || err "failed to delete the pod"
-  "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" wait --for condition=ready pod "${replica}" --timeout=3m \
-    || err "the new pod failed to become ready"
+  # step 10
+  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
+    step "${step_num}" "replica" "${replica}" "Removing temporary directories '${KMDBA_BACKUP_DIR}' and '${KMDBA_RESTORE_DIR}'"
+    exec_pod "${replica}" sh -c "rm --recursive --force ${KMDBA_BACKUP_DIR} ${KMDBA_RESTORE_DIR}" \
+      || err "failed to remove temporary directories"
+  fi
   (( step_num +=1 ))
 
-  step "${step_num}" "replica" "${replica}" "Setting the last change GTID"
-  run_sql_query "${replica}" "RESET REPLICA ALL; SET GLOBAL gtid_slave_pos = \`${gtid}\`;" \
-    || err "failed to set the last change GTID"
+  # step 11
+  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
+    step "${step_num}" "replica" "${replica}" "Recreating the pod"
+    "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" delete pod "${replica}" \
+      || err "failed to delete the pod"
+    "${KMDBA_KUBECTL}" --namespace "${KMDBA_NAMESPACE}" wait --for condition=ready pod "${replica}" --timeout=3m \
+      || err "the new pod failed to become ready"
+  fi
   (( step_num +=1 ))
 
-  step "${step_num}" "cluster" "${mariadb}" "Resuming reconciliation by mariadb-operator"
-  unsuspend_mariadb "${mariadb}"
+  # step 12
+  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
+    step "${step_num}" "replica" "${replica}" "Setting the last change GTID"
+    run_sql_query "${replica}" "RESET REPLICA ALL; SET GLOBAL gtid_slave_pos = \`${KMDBA_GTID}\`;" \
+      || err "failed to set the last change GTID"
+  fi
+  (( step_num +=1 ))
+
+  # step 13
+  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
+    step "${step_num}" "cluster" "${mariadb}" "Resuming reconciliation by mariadb-operator"
+    unsuspend_mariadb "${mariadb}"
+  fi
   (( step_num +=1 ))
 
   # allow mariadb-operator to reconcile replication
   sleep 15
 
-  step "${step_num}" "replica" "${replica}" "Checking replication status"
-  mdb_repl
+  # step 14
+  if [[ "${KMDBA_RECREATE_STEP}" -le "${step_num}" ]]; then
+    step "${step_num}" "replica" "${replica}" "Checking replication status"
+    mdb_repl
+  fi
 
   } 2>&1 | tee "${log_file}"
 
